
services:
  mysql:
    image: mysql:5.5
    container_name: database
    environment: 
      - MYSQL_DATABASE=isp
      - MYSQL_ROOT_PASSWORD=123456
    volumes: 
      - mysql-dump:/var/lib/mysql
    ports: 
      - "3123:3306"

  web_app:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    depends_on:
      - mysql

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - web_app
    ports: 
      - "80:80"

volumes: 
  mysql-dump: