services:
  mysql:
    image: mysql:5.5
    container_name: database
    environment: 
      - MYSQL_DATABASE=isp
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
    volumes: 
      - mysql-dump:/var/lib/mysql
    networks:
      - isp_bridge
    restart: always

  web_app:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - isp_bridge
    restart: always

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - web_app
    ports: 
      - "80:80"
    networks:
      - isp_bridge
    restart: always

networks:
  isp_bridge:

volumes: 
  mysql-dump: